[package]
name = "rust_reddit_cliviewer"
version = "0.1.0"
authors = ["Yashas Lokesh <yashas.lokesh@gmail.com>"]
edition = "2018"

[dependencies]
cursive = "0.12.0"
reqwest = "0.9.18"
webbrowser = "0.5.1"
rand = "0.7.0"
url = "1.7.2"
lazy_static = "1.3.0"